# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.Rwrap_partial_desparsified_lasso_inference <- function(X, y, H, demean, scale, init_partial, nw_partials, init_grid, nw_grids, init_selection_type, nw_selection_types, init_nonzero_limit, nw_nonzero_limits, init_opt_threshold, nw_opt_thresholds, init_opt_type, nw_opt_types, LRVtrunc, T_multiplier, alphas, R, q, PIconstant, PIprobability, manual_Thetahat_, manual_Upsilonhat_inv_, manual_nw_residuals_) {
    .Call(`_desla_Rwrap_partial_desparsified_lasso_inference`, X, y, H, demean, scale, init_partial, nw_partials, init_grid, nw_grids, init_selection_type, nw_selection_types, init_nonzero_limit, nw_nonzero_limits, init_opt_threshold, nw_opt_thresholds, init_opt_type, nw_opt_types, LRVtrunc, T_multiplier, alphas, R, q, PIconstant, PIprobability, manual_Thetahat_, manual_Upsilonhat_inv_, manual_nw_residuals_)
}

.Rwrap_build_gridsXy <- function(T_, N, size, X, y, H, demean, scale) {
    .Call(`_desla_Rwrap_build_gridsXy`, T_, N, size, X, y, H, demean, scale)
}

.Rcpp_local_projection <- function(r_, x, y, q_, y_predetermined, cumulate_y, hmax, lags, alphas, init_partial, selection, PIconstant, progress_bar) {
    .Call(`_desla_Rcpp_local_projection`, r_, x, y, q_, y_predetermined, cumulate_y, hmax, lags, alphas, init_partial, selection, PIconstant, progress_bar)
}

.Rcpp_local_projection_state_dependent <- function(r_, x, y, q_, state_dummy_, y_predetermined, cumulate_y, hmax, lags, alphas, init_partial, selection, PIconstant, progress_bar, OLS, threads) {
    .Call(`_desla_Rcpp_local_projection_state_dependent`, r_, x, y, q_, state_dummy_, y_predetermined, cumulate_y, hmax, lags, alphas, init_partial, selection, PIconstant, progress_bar, OLS, threads)
}

